# Generated by Django 5.2.8 on 2026-02-12 13:42

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcompany',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgood',
            name='article',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='articles.article', verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='historicalgood',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='historicalgood',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrate',
            name='good',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.good', verbose_name='Good'),
        ),
        migrations.AddField(
            model_name='historicalrate',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrate',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='historicaltag',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltype',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rate',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.good', verbose_name='Good'),
        ),
        migrations.AddField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='good',
            name='tag',
            field=models.ManyToManyField(to='shop.tag', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='historicalgood',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.type', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='good',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.type', verbose_name='Type'),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0)), name='Value_must_be_greater_or_equal_0', violation_error_message='Rationgmustbefrom0to5'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rate',
            trigger=pgtrigger.compiler.Trigger(name='soft_dlete_Rate', sql=pgtrigger.compiler.UpsertTriggerSql(func='UPDATE "shop_rate" SET isdeleted = False WHERE "id" = OLD."id"; RETURN NULL;', hash='319795c1c60445266e71923b5152f9e463deeb11', operation='DELETE', pgid='pgtrigger_soft_dlete_rate_7e25a', table='shop_rate', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='good',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='Cost_must_be_greater_or_equal_0', violation_error_message='check_cost'),
        ),
        migrations.AddConstraint(
            model_name='good',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='Amount_must_be_greater_or_equal_0', violation_error_message='check_amount'),
        ),
    ]
