# Generated by Django 5.2.8 on 2026-02-12 13:42

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='historicalorderitem',
            name='good',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.good', verbose_name='Good'),
        ),
        migrations.AddField(
            model_name='historicalorderitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorderitem',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='historicalorderitem',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cart.order', verbose_name='OrderId'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.good', verbose_name='Good'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_order', to='cart.order', verbose_name='OrderId'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderitem',
            field=models.ManyToManyField(through='cart.OrderItem', through_fields=('order', 'good'), to='shop.good', verbose_name='Order item'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='order',
            trigger=pgtrigger.compiler.Trigger(name='read_only', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."date" IS DISTINCT FROM (NEW."date"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='b73658a8df6bb3c99d031e60da0333f11e23c833', operation='UPDATE', pgid='pgtrigger_read_only_64dac', table='cart_order', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='order',
            trigger=pgtrigger.compiler.Trigger(name='soft_dlete_order', sql=pgtrigger.compiler.UpsertTriggerSql(func='UPDATE "cart_order" SET isdeleted = False WHERE "id" = OLD."id"; RETURN NULL;', hash='19de17d352ef529fe8a231edce3776a299a4f370', operation='DELETE', pgid='pgtrigger_soft_dlete_order_600b2', table='cart_order', when='BEFORE')),
        ),
    ]
